select * from behavior limit 20;

-- Total revenue generated by male vs female customers
select gender, sum(purchase_amount) 
as total_revenue 
from behavior 
group by gender;

-- Customers used discount but still spent more than average purcahase amount
select customer_id, purchase_amount 
from behavior 
where discount_applied='Yes' and purchase_amount >= (select avg(purchase_amount) from behavior); 

--Top 5 products with highest average review rating
select item_purchased, round(avg(review_rating::numeric),2) as avg_product_rating
from behavior 
group by item_purchased 
order by avg_product_rating desc limit 5;

--Comare the average puchase amount between standard and express shooping
select shipping_type, round(avg(purchase_amount),2) as avg_purchase_amount 
from behavior 
where shipping_type in ('Standard','Express') 
group by shipping_type;

--Compare average spend and total spend between subsciber and non-subscriber
select subscription_status, round(avg(purchase_amount),2) as avg_purchase_amount, 
sum(purchase_amount) as total_purchase_amount 
from behavior 
group by subscription_status;

--Which 5 products have the highest percentage of purchases amount with discount applied
select item_purchased, sum(purchase_amount) as total_purchase_amount, 
sum(case when discount_applied='Yes' then purchase_amount else 0 end) 
as total_discount_purchase_amount 
from behavior 
group by item_purchased 
order by total_purchase_amount 
desc limit 5;

--Segment customers into New, Returning and Loyal based on the total number of previous purchase history
with customer_type as 
(SELECT customer_id, previous_purchases, 
case 
    when previous_purchases=1 then 'New' 
    when previous_purchases BETWEEN 0 and 10 then 'Returning' 
    else 'Loyal' 
    end as customer_segment from behavior
)
select customer_segment, count(*) as "Number of Customers"
from customer_type
group by customer_segment;

--Top 3 most purchased products within each category
with item_counts as (
    select category, item_purchased, count(customer_id) 
    as total_orders,
    row_number() over (partition by category order by count(customer_id) desc) as item_rank
    from behavior
    group by category, item_purchased
)
select item_rank,category,item_purchased,total_orders
from item_counts
where item_rank<=3;

--Are customeers who are repeat customers (more than 5 previous purcahses) also likely to subscribe to the service?
select subscription_status, count(customer_id) as repeat_customer
from behavior
where previous_purchases>5
group by subscription_status;

--Revenue generated by each age group
select age_group, sum(purchase_amount) as total_revenue
from behavior
group by age_group
order by total_revenue desc;